export type ProviderKind = "text_corpus" | "scholarly_index" | "museum_archive" | "archaeology" | "geography" | "paleoclimate" | "paleoecology";
export type AccessMode = "open_no_key" | "api_key" | "client_credentials" | "manual_download" | "metadata_only" | "review_required";

export interface ProviderDefinition {
  key: string;
  name: string;
  kind: ProviderKind;
  homepage: string;
  apiBase?: string;
  cultures: string[];
  scope: string;
  access: AccessMode;
  status: "connected" | "configured" | "needs_credentials" | "cataloged" | "paused";
  rightsLane: "green" | "yellow" | "red";
  rightsNote: string;
  attribution?: string;
  termsUrl?: string;
  environmentKey?: string;
  capabilities: string[];
  enabled: boolean;
}

export const providerRegistry: ProviderDefinition[] = [
  { key:"world_english_bible",name:"World English Bible Classic",kind:"text_corpus",homepage:"https://ebible.org/details.php?id=eng-web",apiBase:"https://ebible.org/eng-web",cultures:["Biblical","Ancient Israelite","Early Christian"],scope:"Public-domain English Bible edition with stable book, chapter, and verse locators.",access:"open_no_key",status:"connected",rightsLane:"green",rightsNote:"The Classic World English Bible text is dedicated to the public domain. Preserve the exact edition identity; modified text may not retain the World English Bible name.",attribution:"World English Bible Classic, eBible.org; public domain",termsUrl:"https://ebible.org/details.php?id=eng-web",capabilities:["chapter_import","verse_locator","public_domain_text"],enabled:true },
  { key:"gutenberg",name:"Project Gutenberg",kind:"text_corpus",homepage:"https://www.gutenberg.org",apiBase:"https://www.gutenberg.org/ebooks/search.opds/",cultures:["Global","Ancient Near Eastern","Greek","Indian","Biblical"],scope:"Public-domain ebooks and historical translations discoverable through the official OPDS catalog.",access:"open_no_key",status:"connected",rightsLane:"green",rightsNote:"Catalog metadata is public domain. Every ebook retains its embedded Project Gutenberg license and a United States public-domain jurisdiction warning; edition text is imported only after item review.",attribution:"Project Gutenberg ebook and embedded license",termsUrl:"https://www.gutenberg.org/policy/terms_of_use.html",capabilities:["opds_search","ebook_metadata","reviewed_text_import"],enabled:true },
  { key:"wikisource",name:"Wikisource",kind:"text_corpus",homepage:"https://wikisource.org",apiBase:"https://en.wikisource.org/w/api.php",cultures:["Global","Biblical","Indian","Greek","Chinese","Mesoamerican"],scope:"Proofread public-domain and openly licensed source texts, editions, and translations on Wikimedia projects.",access:"open_no_key",status:"connected",rightsLane:"yellow",rightsNote:"Page and edition licensing, contributor attribution, revision ID, and source scan status must be preserved. Search results are staged as references until reviewed.",attribution:"Wikisource contributors",termsUrl:"https://foundation.wikimedia.org/wiki/Policy:Terms_of_Use",capabilities:["page_search","revision_metadata","page_extract"],enabled:true },
  { key:"wikipedia",name:"Wikipedia",kind:"scholarly_index",homepage:"https://www.wikipedia.org",apiBase:"https://en.wikipedia.org/w/api.php",cultures:["Global"],scope:"Reference summaries and bibliographies used to discover primary sources, scholarship, entities, places, and terminology.",access:"open_no_key",status:"connected",rightsLane:"yellow",rightsNote:"CC BY-SA reference material is a research lead, not primary evidence. Preserve page URL, revision timestamp, attribution, and cited-source verification tasks.",attribution:"Wikipedia contributors, CC BY-SA",termsUrl:"https://foundation.wikimedia.org/wiki/Policy:Terms_of_Use",capabilities:["reference_search","page_extract","bibliography_discovery"],enabled:true },
  { key:"wikidata",name:"Wikidata",kind:"scholarly_index",homepage:"https://www.wikidata.org",apiBase:"https://www.wikidata.org/w/api.php",cultures:["Global"],scope:"CC0 entity identifiers, aliases, dates, coordinates, and links used for entity reconciliation.",access:"open_no_key",status:"connected",rightsLane:"green",rightsNote:"Structured data is CC0, but specialist dates and claims still require source verification before publication.",attribution:"Wikidata contributors, CC0",termsUrl:"https://www.wikidata.org/wiki/Wikidata:Data_access",capabilities:["entity_search","entity_lookup","identifier_reconciliation"],enabled:true },
  { key:"oracc",name:"ORACC",kind:"text_corpus",homepage:"https://oracc.museum.upenn.edu",apiBase:"https://oracc.museum.upenn.edu/json",cultures:["Sumerian","Akkadian","Babylonian","Assyrian"],scope:"Open Richly Annotated Cuneiform Corpus project metadata, compositions, transliterations, translations, and glossaries.",access:"review_required",status:"cataloged",rightsLane:"yellow",rightsNote:"Confirm the selected ORACC subproject license and attribution before text ingestion; preserve project, composition, tablet, and line identifiers.",attribution:"ORACC project contributors",termsUrl:"https://oracc.museum.upenn.edu/doc/about/licensing/index.html",capabilities:["project_catalog","composition_metadata","line_reference"],enabled:false },
  { key:"sefaria",name:"Sefaria",kind:"text_corpus",homepage:"https://www.sefaria.org",apiBase:"https://www.sefaria.org/api",cultures:["Jewish","Ancient Israelite","Rabbinic"],scope:"Tanakh, Mishnah, Talmud, Midrash, halakhah, philosophy, and related Jewish texts.",access:"review_required",status:"configured",rightsLane:"yellow",rightsNote:"License is version-specific. Metadata and exact references may be staged; text remains blocked until the selected version license is recorded.",attribution:"Text/version attribution supplied by Sefaria must be preserved.",termsUrl:"https://developers.sefaria.org/docs/usage-of-our-name-and-logo",capabilities:["exact_reference","version_metadata","text_by_version"],enabled:true },
  { key:"quran_foundation",name:"Quran Foundation API",kind:"text_corpus",homepage:"https://quran.com/developers",apiBase:"https://apis.quran.foundation",cultures:["Islamic","Arabic"],scope:"Quran chapters, verses, translations, tafsir metadata, recitations, and word analysis.",access:"client_credentials",status:"needs_credentials",rightsLane:"yellow",rightsNote:"Arabic text and each translation/tafsir resource require their supplied attribution and usage terms. No content is imported without credentials and review.",environmentKey:"QURAN_CLIENT_ID,QURAN_CLIENT_SECRET",capabilities:["verse_lookup","translation_catalog","tafsir_catalog"],enabled:false },
  { key:"tanzil",name:"Tanzil Quran Text",kind:"text_corpus",homepage:"https://tanzil.net/download",cultures:["Islamic","Arabic"],scope:"Verified Arabic Quran text downloads.",access:"manual_download",status:"cataloged",rightsLane:"yellow",rightsNote:"Arabic text must remain unmodified and the Tanzil attribution/license notice must be preserved. Manual controlled import only.",attribution:"Tanzil Project",termsUrl:"https://tanzil.net/docs/Text_License",capabilities:["manual_text_import"],enabled:false },
  { key:"perseus",name:"Perseus / Scaife CTS",kind:"text_corpus",homepage:"https://www.perseus.tufts.edu",apiBase:"https://scaife-cts.perseus.org/api/cts",cultures:["Greek","Roman","Near Eastern"],scope:"Classical Greek and Latin editions and translations, including Plato and ancient historiography.",access:"review_required",status:"configured",rightsLane:"yellow",rightsNote:"Edition and translation rights vary. CTS URNs and catalog metadata may be staged before text rights review.",attribution:"Perseus Digital Library / edition contributor",capabilities:["cts_catalog","urn_lookup","passage_lookup"],enabled:false },
  { key:"ctext",name:"Chinese Text Project",kind:"text_corpus",homepage:"https://ctext.org",apiBase:"https://api.ctext.org",cultures:["Chinese"],scope:"Pre-Qin and Han through later Chinese philosophical and historical texts.",access:"review_required",status:"cataloged",rightsLane:"yellow",rightsNote:"API access and reuse terms must be confirmed for the requested material. Stage references and metadata first.",termsUrl:"https://ctext.org/tools/api",capabilities:["work_catalog","passage_reference"],enabled:false },
  { key:"gretil",name:"GRETIL",kind:"text_corpus",homepage:"https://gretil.sub.uni-goettingen.de",cultures:["Vedic","Sanskrit","Indian","Buddhist","Jain"],scope:"Electronic texts in Sanskrit and other Indian languages, including Vedic and epic materials.",access:"manual_download",status:"cataloged",rightsLane:"yellow",rightsNote:"Files have edition-specific provenance and reuse notes. Manual review is required before passage ingestion.",capabilities:["manual_text_import","bibliography"],enabled:false },
  { key:"bdrc",name:"Buddhist Digital Resource Center",kind:"text_corpus",homepage:"https://www.bdrc.io",apiBase:"https://ldspdi.bdrc.io",cultures:["Tibetan","Buddhist","Himalayan"],scope:"Buddhist works, persons, places, scans, and linked bibliographic records.",access:"review_required",status:"cataloged",rightsLane:"yellow",rightsNote:"Metadata and image/text rights vary by resource and partner. Preserve BDRC identifiers and access statements.",capabilities:["linked_data","work_catalog","scan_metadata"],enabled:false },
  { key:"sat",name:"SAT Daizōkyō Database",kind:"text_corpus",homepage:"https://21dzk.l.u-tokyo.ac.jp/SAT/",cultures:["Chinese Buddhist","Japanese Buddhist"],scope:"Taishō canon research database and related Buddhist textual resources.",access:"review_required",status:"cataloged",rightsLane:"yellow",rightsNote:"Use as a discovery/reference provider until explicit API and text-reuse terms are approved.",capabilities:["reference_discovery"],enabled:false },
  { key:"loc",name:"Library of Congress",kind:"museum_archive",homepage:"https://www.loc.gov",apiBase:"https://www.loc.gov",cultures:["Global","American","Mesoamerican","African","Asian"],scope:"Digitized books, manuscripts, maps, photographs, and collection metadata.",access:"open_no_key",status:"connected",rightsLane:"yellow",rightsNote:"Catalog metadata can be staged. Rights statements remain item-specific; digitization does not imply public domain.",attribution:"Library of Congress",termsUrl:"https://www.loc.gov/apis/",capabilities:["metadata_search","item_lookup","digital_resources"],enabled:true },
  { key:"europeana",name:"Europeana",kind:"museum_archive",homepage:"https://www.europeana.eu",apiBase:"https://api.europeana.eu/record/v2",cultures:["European","Mediterranean","Global collections"],scope:"Cultural heritage metadata and IIIF media from European institutions.",access:"api_key",status:"needs_credentials",rightsLane:"yellow",rightsNote:"Metadata is searchable by key; each object retains its own rights statement and provider attribution.",environmentKey:"EUROPEANA_API_KEY",capabilities:["metadata_search","record_lookup","iiif"],enabled:false },
  { key:"smithsonian",name:"Smithsonian Open Access",kind:"museum_archive",homepage:"https://www.si.edu/openaccess",apiBase:"https://api.si.edu/openaccess/api/v1.0",cultures:["Global","American","African","Asian","Indigenous"],scope:"Museum, archive, library, and research collection metadata and open assets.",access:"api_key",status:"needs_credentials",rightsLane:"yellow",rightsNote:"CC0 assets can enter Green after record-level verification; non-open records remain metadata-only.",attribution:"Smithsonian Institution",environmentKey:"SMITHSONIAN_API_KEY",capabilities:["metadata_search","record_lookup","open_assets"],enabled:false },
  { key:"internet_archive",name:"Internet Archive",kind:"museum_archive",homepage:"https://archive.org",apiBase:"https://archive.org/advancedsearch.php",cultures:["Global"],scope:"Scanned books, media, and metadata used for discovery and edition identification.",access:"metadata_only",status:"configured",rightsLane:"yellow",rightsNote:"Internet Archive presence is not proof of public-domain status. Origin Graph uses it for discovery/metadata until rights are independently verified.",capabilities:["metadata_search","edition_discovery"],enabled:true },
  { key:"pleiades",name:"Pleiades",kind:"geography",homepage:"https://pleiades.stoa.org",apiBase:"https://api.pleiades.stoa.org",cultures:["Ancient Mediterranean","Near Eastern"],scope:"Ancient places, names, locations, and temporal attestations.",access:"open_no_key",status:"connected",rightsLane:"green",rightsNote:"Data may be used with required Pleiades contributor attribution under CC BY 3.0.",attribution:"Pleiades contributors, CC BY 3.0",termsUrl:"https://pleiades.stoa.org/credits",capabilities:["place_lookup","geojson","names"],enabled:true },
  { key:"open_context",name:"Open Context",kind:"archaeology",homepage:"https://opencontext.org",apiBase:"https://opencontext.org/query",cultures:["Global archaeology"],scope:"Published archaeological datasets, objects, sites, and linked records.",access:"review_required",status:"cataloged",rightsLane:"yellow",rightsNote:"Dataset licenses and sensitive-site controls are record-specific. Import metadata and public geometry only after review.",capabilities:["dataset_search","object_metadata","public_geometry"],enabled:false },
  { key:"noaa_paleo",name:"NOAA/WDS Paleoclimatology",kind:"paleoclimate",homepage:"https://www.ncei.noaa.gov/products/paleoclimatology",apiBase:"https://www.ncei.noaa.gov/access/paleo-search/study/search.json",cultures:["Global scientific"],scope:"Paleoclimate studies, proxy records, reconstructions, and dataset metadata.",access:"open_no_key",status:"connected",rightsLane:"green",rightsNote:"Stage study metadata, investigator attribution, dataset links, methods, and chronology. Scientific interpretation remains a separate reviewed claim.",attribution:"NOAA National Centers for Environmental Information",capabilities:["study_search","dataset_metadata","site_geometry"],enabled:true },
  { key:"neotoma",name:"Neotoma Paleoecology Database",kind:"paleoecology",homepage:"https://www.neotomadb.org",apiBase:"https://api.neotomadb.org",cultures:["Global scientific"],scope:"Fossil, paleoecological, paleoenvironmental, chronology, and publication records for the last 5.2 million years.",access:"open_no_key",status:"configured",rightsLane:"green",rightsNote:"Preserve contributor, dataset, chronology-model, and publication provenance. Do not infer cultural claims from proxy records.",attribution:"Neotoma Paleoecology Database",capabilities:["dataset_search","site_lookup","chronology"],enabled:false },
  { key:"paleobiodb",name:"Paleobiology Database",kind:"paleoecology",homepage:"https://paleobiodb.org",apiBase:"https://paleobiodb.org/data1.2",cultures:["Global scientific"],scope:"Fossil occurrences, taxa, collections, references, and geological intervals.",access:"open_no_key",status:"connected",rightsLane:"green",rightsNote:"Preserve record references and database attribution. Fossil records remain empirical observations, not direct evidence for textual claims.",attribution:"Paleobiology Database",capabilities:["occurrence_search","taxon_lookup","reference_lookup"],enabled:true },
  { key:"crossref",name:"Crossref",kind:"scholarly_index",homepage:"https://www.crossref.org",apiBase:"https://api.crossref.org",cultures:["Global scholarly"],scope:"DOI metadata for scholarship across archaeology, history, religion, paleoclimate, and human origins.",access:"open_no_key",status:"connected",rightsLane:"yellow",rightsNote:"Bibliographic metadata is staged; abstract/full-text reuse follows publisher and work-level rights.",attribution:"Crossref",capabilities:["work_search","doi_lookup","citation_metadata"],enabled:true },
  { key:"openalex",name:"OpenAlex",kind:"scholarly_index",homepage:"https://openalex.org",apiBase:"https://api.openalex.org",cultures:["Global scholarly"],scope:"Scholarly works, authors, institutions, topics, citations, and open-access locations.",access:"api_key",status:"needs_credentials",rightsLane:"yellow",rightsNote:"Index metadata is open; linked work content and abstracts retain record-level rights. Retraction and OA fields must be preserved.",environmentKey:"OPENALEX_API_KEY",capabilities:["work_search","citation_graph","open_access_status","retraction_status"],enabled:false }
];
