import { NextResponse, type NextRequest } from "next/server";
import { z } from "zod";
import { db, transaction } from "@/db";
import { appendAudit } from "@/domain/services";
import { apiError, requestActor } from "@/http";

const patchSchema=z.object({statement:z.string().min(3).optional(),claim_class:z.string().min(1).optional(),directness:z.number().int().min(0).max(4).optional(),interpretation_level:z.number().int().min(0).max(4).optional(),uncertainty_note:z.string().nullable().optional()});
export async function GET(_request:Request,context:{params:Promise<{id:string}>}){const {id}=await context.params;const result=await db().query(`SELECT c.*,p.locator_type,p.locator_value,p.original_text,p.transliteration,p.translation_text,p.safe_summary,se.id AS source_id,se.title AS source_title,se.license_name,se.license_url,se.attribution_text FROM claims c LEFT JOIN passages p ON p.id=c.passage_id LEFT JOIN source_editions se ON se.id=p.source_edition_id WHERE c.id=$1`,[id]);if(!result.rows[0])return NextResponse.json({error:{code:"NOT_FOUND",message:"Claim not found",details:{}}},{status:404});return NextResponse.json(result.rows[0]);}
export async function PATCH(request:NextRequest,context:{params:Promise<{id:string}>}){try{const {id}=await context.params;const input=patchSchema.parse(await request.json());const actor=requestActor(request);const result=await transaction(db(),async client=>{const before=await client.query("SELECT * FROM claims WHERE id=$1 FOR UPDATE",[id]);if(!before.rows[0])throw new Error("NOT_FOUND: claim not found");const after=await client.query(`UPDATE claims SET statement=coalesce($2,statement),claim_class=coalesce($3,claim_class),directness=coalesce($4,directness),interpretation_level=coalesce($5,interpretation_level),uncertainty_note=CASE WHEN $6 THEN $7 ELSE uncertainty_note END,updated_at=now() WHERE id=$1 RETURNING *`,[id,input.statement,input.claim_class,input.directness,input.interpretation_level,Object.hasOwn(input,"uncertainty_note"),input.uncertainty_note]);await appendAudit(client,{objectType:"claim",objectId:id,action:"edited",actor,before:before.rows[0],after:after.rows[0]});return after.rows[0];});return NextResponse.json(result);}catch(error){return apiError(error);}}
