"use client";
import { use, useCallback, useEffect, useState } from "react";

export default function CaseFilePage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = use(params);
  const [file, setFile] = useState<Record<string, any> | null>(null);
  const load = useCallback(() => fetch(`/api/case-files/${slug}`).then((response) => response.json()).then(setFile), [slug]);
  useEffect(() => { load(); }, [load]);
  if (!file) return <main className="standard-page"><p className="empty-state">Loading case file…</p></main>;
  const claims = file.claims ?? []; const sources = file.sources ?? []; const motifs = file.motifs ?? [];
  const candidates = Array.isArray(file.source_candidates) ? file.source_candidates : [];
  const selected = candidates.filter((source: any) => source.review_status === "approved");
  const sections = ["Primary sources", "Chronology", "Places", "Motifs", "Support & challenge", "Alternatives", "Open questions", "Sources & rights", "Revision history"];
  return <main className="standard-page">
    <header className="page-header case-hero"><div><p className="eyebrow">Case file · {file.review_status}</p><h1>{file.title}</h1><p><a className="text-link" href={`/api/case-files/${slug}/export?format=markdown`}>Export research dossier</a></p></div><p>{file.core_question}</p></header>
    <div className="case-metrics"><div><b>{claims.length}</b><span>reviewed claims</span></div><div><b>{sources.length}</b><span>source records</span></div><div><b>{selected.length}</b><span>selected leads</span></div><div><b>{motifs.length}</b><span>coded motifs</span></div></div>
    <div className="case-layout"><aside><b>Investigation</b>{sections.map((section,index)=><a href={`#section-${index}`} key={section}>{String(index+1).padStart(2,"0")} {section}</a>)}</aside><div>
      <section className="case-section" id="section-0"><span>01</span><div><h2>What primary sources state</h2><div className="case-claim-ledger">{claims.map((claim:any)=><article key={claim.id}><header><b>{claim.claim_class.replaceAll("_"," ")}</b><span>{claim.evidence_role.replaceAll("_"," ")}</span></header><p>{claim.statement}</p><footer><a href={`/sources/${claim.source_id}`}>{claim.source_title}</a><code>{claim.locator}</code></footer>{claim.uncertainty_note&&<small>{claim.uncertainty_note}</small>}</article>)}</div>{!claims.length&&<p>No reviewed exact-locator claim is attached yet. Discovery records below are not evidence.</p>}</div></section>
      <section className="case-section" id="section-1"><span>02</span><div><h2>Chronology</h2><p>Date roles stay separate on the living timeline: narrative event, composition, physical witness, edition, observation, and natural phenomenon.</p><a className="small-button" href={`/?case=${slug}`}>Open timeline workspace</a></div></section>
      <section className="case-section" id="section-2"><span>03</span><div><h2>Places & uncertainty</h2><p>Literary or disputed places never become factual map pins. Approximate and protected geometry remains visibly labeled.</p><a className="small-button" href="/map">Inspect reviewed map</a></div></section>
      <section className="case-section" id="section-3"><span>04</span><div><h2>Motifs, not identities</h2><div className="case-motif-row">{motifs.map((motif:any)=><article key={motif.id}><h3>{motif.label}</h3><p>{motif.definition}</p></article>)}</div>{!motifs.length&&<p>No comparative motif has passed review for this file.</p>}</div></section>
      <section className="case-section" id="section-4"><span>05</span><div><h2>Support & challenge</h2><p>Evidence stances live on hypothesis cards, not on popularity or truth scores.</p>{(file.hypotheses??[]).map((hypothesis:any)=><a className="case-hypothesis" href={`/hypotheses/${hypothesis.id}`} key={hypothesis.id}><b>{hypothesis.title}</b><span>{hypothesis.state}</span><p>{hypothesis.proposition}</p></a>)}{!(file.hypotheses??[]).length&&<p>No frontier hypothesis is attached; the case remains descriptive.</p>}</div></section>
      <section className="case-section" id="section-5"><span>06</span><div><h2>Alternative explanations</h2>{(file.hypotheses??[]).flatMap((hypothesis:any)=>hypothesis.alternatives??[]).map((value:string)=><p className="case-alternative" key={value}>{value}</p>)}{!(file.hypotheses??[]).length&&<p>Alternatives are required before an explanatory hypothesis can become active.</p>}</div></section>
      <section className="case-section" id="section-6"><span>07</span><div><h2>Open questions</h2>{(file.saved_queries??[]).map((query:any)=><p key={query.id}>{query.question}</p>)}{!(file.saved_queries??[]).length&&<p>Which primary text, material observation, or independent source family would change the current evidence packet?</p>}</div></section>
      <section className="case-section" id="section-7"><span>08</span><div><h2>Sources & rights</h2><div className="case-sources">{selected.map((source:any)=><article key={source.id}><header><span>{source.provider}</span><b className={`rights-${source.rights_lane}`}>{source.rights_lane}</b></header><h3>{source.title}</h3><p>{source.relevance_note}</p><footer>{source.canonical_url?<a href={source.canonical_url} target="_blank" rel="noreferrer">Inspect upstream ↗</a>:<span>No stable URL</span>}<small>{source.record_type} · metadata selected</small></footer></article>)}</div><p className="form-note">{candidates.length-selected.length} discovery candidates remain blocked or unselected. Archive presence alone never proves public-domain status.</p></div></section>
      <section className="case-section" id="section-8"><span>09</span><div><h2>Revision history</h2>{(file.revisions??[]).map((revision:any)=><article className="revision-row" key={revision.id}><b>Revision {revision.revision_number}</b><span>{revision.reason}</span><small>{revision.actor} · {new Date(revision.created_at).toLocaleString()}</small></article>)}{!(file.revisions??[]).length&&<p>No editorial revision snapshot has been published yet.</p>}</div></section>
    </div></div>
  </main>;
}
