"use client";

import { useState,type FormEvent } from "react";

export function HypothesisEditor({id,item,onSaved}:{id:string;item:Record<string,any>;onSaved:()=>void}){
  const [open,setOpen]=useState(false);const [message,setMessage]=useState('');
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const list=(key:string)=>String(form.get(key)??'').split('\n').map(value=>value.trim()).filter(Boolean);const response=await fetch(`/api/hypotheses/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:form.get('title'),proposition:form.get('proposition'),scope:form.get('scope'),state:form.get('state'),predicted_observations:list('predictions'),falsifiers:list('falsifiers'),alternatives:list('alternatives'),reason:form.get('reason')})});const data=await response.json();if(!response.ok){setMessage(data.error?.message??'Could not save revision.');return;}setMessage('Revision saved.');setOpen(false);onSaved();}
  return <section className="hypothesis-controls"><div><button className="small-button" onClick={()=>setOpen(value=>!value)}>{open?'Cancel revision':'Revise hypothesis'}</button><a href={`/api/hypotheses/${id}/export?format=markdown`}>Export report</a><span>{item.revisions?.length??0} revisions</span></div>{message&&<p className="form-note">{message}</p>}{open&&<form className="hypothesis-editor" onSubmit={submit}><label>Title<input name="title" defaultValue={item.title} required/></label><label>State<select name="state" defaultValue={item.state}>{['draft','active','paused','rejected','supported','superseded'].map(value=><option key={value}>{value}</option>)}</select></label><label className="full">Precise proposition<textarea name="proposition" defaultValue={item.proposition} required/></label><label className="full">Scope and definitions<textarea name="scope" defaultValue={item.scope} required/></label><label>Predicted observations<textarea name="predictions" defaultValue={(item.predicted_observations??[]).join('\n')}/></label><label>Falsifiers<textarea name="falsifiers" defaultValue={(item.falsifiers??[]).join('\n')}/></label><label className="full">Alternatives<textarea name="alternatives" defaultValue={(item.alternatives??[]).join('\n')} required/></label><label className="full">Revision reason<input name="reason" placeholder="What changed and why?" required/></label><button className="solid-button">Save reversible revision</button></form>}</section>;
}
