"use client";

import { useEffect, useMemo, useState, type FormEvent } from "react";

interface Provider { provider_key:string;display_name:string;provider_kind:string;access_mode:string;connector_status:string;rights_lane:string;enabled:boolean;staged_records:number;last_checked_at:string|null }
interface Candidate { external_id:string;record_type:string;title:string;subtitle?:string;canonical_url?:string;date_label?:string;creators:string[];places:string[];subjects:string[];rights_uri?:string;rights_lane:"green"|"yellow"|"red";rights_note:string;safe_summary?:string;raw_metadata:Record<string,unknown> }

const kindLabels:Record<string,string>={text_corpus:"Texts",scholarly_index:"Scholarship",museum_archive:"Archives",archaeology:"Archaeology",geography:"Places",paleoclimate:"Climate",paleoecology:"Deep time"};

export function ProviderCatalog(){
  const [providers,setProviders]=useState<Provider[]>([]);const [filter,setFilter]=useState("all");const [selected,setSelected]=useState<Provider|null>(null);const [query,setQuery]=useState("");const [results,setResults]=useState<Candidate[]>([]);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");
  useEffect(()=>{fetch('/api/providers').then(r=>r.json()).then(data=>setProviders(data.providers??[]));const seededQuery=new URLSearchParams(window.location.search).get('query');if(seededQuery){setQuery(seededQuery);setMessage('Choose a connected collection, then search for this topic.');}},[]);
  const shown=useMemo(()=>filter==='all'?providers:providers.filter(provider=>provider.provider_kind===filter),[providers,filter]);
  async function search(event:FormEvent){event.preventDefault();if(!selected)return;setBusy(true);setMessage("");setResults([]);const response=await fetch(`/api/providers/${selected.provider_key}/search`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query})});const data=await response.json();if(response.ok)setResults(data.results??[]);else setMessage(data.error?.message??'Search failed.');setBusy(false);}
  async function stage(candidate:Candidate){if(!selected)return;const response=await fetch(`/api/providers/${selected.provider_key}/stage`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(candidate)});const data=await response.json();setMessage(response.ok?`Staged “${candidate.title}” for human review.`:data.error?.message??'Could not stage record.');}
  return <div className="provider-workspace">
    <div className="provider-toolbar"><div className="segmented-control" role="tablist"><button aria-selected={filter==='all'} onClick={()=>setFilter('all')}>All</button>{Object.entries(kindLabels).map(([key,label])=><button aria-selected={filter===key} onClick={()=>setFilter(key)} key={key}>{label}</button>)}</div><p><strong>{providers.filter(p=>p.connector_status==='connected').length}</strong> live · <strong>{providers.length}</strong> governed providers</p></div>
    <div className="provider-grid">{shown.map(provider=><button className={`provider-card ${selected?.provider_key===provider.provider_key?'selected':''}`} onClick={()=>{setSelected(provider);setResults([]);setMessage('');}} key={provider.provider_key}><span className="provider-kind">{kindLabels[provider.provider_kind]??provider.provider_kind}</span><strong>{provider.display_name}</strong><span className="provider-state"><i className={`health-dot ${provider.connector_status}`}/>{provider.connector_status.replaceAll('_',' ')}</span><footer><span className={`pill lane-${provider.rights_lane}`}>{provider.rights_lane}</span><span>{provider.staged_records} staged</span></footer></button>)}</div>
    {selected&&<aside className="provider-drawer" aria-live="polite"><header><div><span className="eyebrow">{kindLabels[selected.provider_kind]} provider</span><h2>{selected.display_name}</h2></div><button aria-label="Close provider" onClick={()=>setSelected(null)}>Close</button></header><div className="provider-drawer-meta"><span><b>Connection</b>{selected.connector_status.replaceAll('_',' ')}</span><span><b>Access</b>{selected.access_mode.replaceAll('_',' ')}</span><span><b>Rights default</b>{selected.rights_lane}</span></div>{selected.enabled?<form className="provider-search" onSubmit={search}><label>Search provider<input value={query} onChange={event=>setQuery(event.target.value)} placeholder={selected.provider_key==='pleiades'?'Enter a numeric Pleiades place ID':'Search title, person, place, or topic'} required minLength={2}/></label><button className="solid-button" disabled={busy}>{busy?'Searching…':'Search live catalog'}</button></form>:<p className="connector-notice">This connector is cataloged but gated by credentials, edition rights, or editorial approval. Its coverage is visible without pretending the data is already ingested.</p>}{message&&<p className="form-note">{message}</p>}<div className="candidate-list">{results.map(candidate=><article key={candidate.external_id}><header><span className="kicker">{candidate.record_type.replaceAll('_',' ')}</span><span className={`pill lane-${candidate.rights_lane}`}>{candidate.rights_lane}</span></header><h3>{candidate.title}</h3>{candidate.safe_summary&&<p>{candidate.safe_summary}</p>}<small>{[candidate.date_label,...candidate.creators,...candidate.places].filter(Boolean).join(' · ')}</small><footer>{candidate.canonical_url&&<a href={candidate.canonical_url} target="_blank" rel="noreferrer">Open provider record</a>}<button onClick={()=>stage(candidate)}>Stage for review</button></footer></article>)}</div></aside>}
  </div>;
}
