"use client";

import { useState, type FormEvent } from "react";

type Tab="answer"|"evidence"|"chronology"|"citations";
const roles=[['primary_tradition','Primary texts'],['physical_scientific','Scientific'],['academic_interpretation','Scholarship'],['modern_discourse','Modern leads']] as const;
const examples=["Compare reviewed flood traditions by date role and source family","What is the evidence around the Younger Dryas transition?","What do reviewed editions say about Atlantis in Plato?","Compare reported sacred-teacher roles without collapsing traditions"];

export default function AskPage(){
  const [question,setQuestion]=useState('');const [selectedRoles,setSelectedRoles]=useState<string[]>([]);const [fromYear,setFromYear]=useState('');const [toYear,setToYear]=useState('');const [result,setResult]=useState<Record<string,any>|null>(null);const [loading,setLoading]=useState(false);const [tab,setTab]=useState<Tab>('answer');const [message,setMessage]=useState('');
  async function submit(event:FormEvent){event.preventDefault();setLoading(true);setMessage('');const filters={evidence_roles:selectedRoles.length?selectedRoles:undefined,from_year:fromYear?Number(fromYear):undefined,to_year:toYear?Number(toYear):undefined};const response=await fetch('/api/ask',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question,filters})});setResult(await response.json());setLoading(false);setTab('answer');}
  function toggleRole(role:string){setSelectedRoles(current=>current.includes(role)?current.filter(item=>item!==role):[...current,role]);}
  async function saveHypothesis(){if(!result?.suggested_hypothesis)return;setMessage('Creating private hypothesis…');const seed=result.suggested_hypothesis;const response=await fetch('/api/hypotheses',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({slug:`ask-${Date.now()}`,title:seed.title,proposition:seed.proposition,scope:seed.scope,predictions:[],falsifiers:[],alternatives:seed.alternatives})});const data=await response.json();if(!response.ok){setMessage(data.error?.message??'Could not create hypothesis.');return;}for(const claimId of seed.claim_ids??[]){await fetch(`/api/hypotheses/${data.id}/evidence`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({claim_id:claimId,stance:'contextualizes',evidence_domain:'Ask evidence packet',reviewer_note:`Imported from question: ${question}`})});}window.location.href=`/hypotheses/${data.id}`;}
  return <main className="ask-workbench"><section className="ask-command"><div className="ask-command-copy"><p className="eyebrow">Evidence workbench</p><h1>Ask across time,<br/>texts, and traces.</h1><p>Every factual sentence must resolve to a reviewed locator. Dependent sources count once. Missing evidence stays missing.</p></div><form onSubmit={submit}><label className="ask-question-label">Research question<textarea value={question} onChange={event=>setQuestion(event.target.value)} placeholder="Ask a comparative question…" required minLength={3}/></label><div className="ask-filter-row"><fieldset><legend>Evidence lanes</legend>{roles.map(([role,label])=><button type="button" aria-pressed={selectedRoles.includes(role)} onClick={()=>toggleRole(role)} key={role}>{label}</button>)}</fieldset><label>From year<input type="number" value={fromYear} onChange={event=>setFromYear(event.target.value)} placeholder="-12000"/></label><label>To year<input type="number" value={toYear} onChange={event=>setToYear(event.target.value)} placeholder="2026"/></label><button className="ask-run" disabled={loading}>{loading?'Assembling packet…':'Build evidence packet'}<span>↗</span></button></div></form><div className="ask-examples"><span>Try a research frame</span>{examples.map(example=><button onClick={()=>setQuestion(example)} key={example}>{example}</button>)}</div></section>
    {result?.error&&<section className="ask-results"><p className="error-box">{result.error.message}</p></section>}
    {result&&!result.error&&<section className="ask-results"><header className="answer-status-bar"><div><span className={`answer-signal ${result.answer_status}`}/><b>{result.answer_status}</b><span>{result.source_counts.passages} passages · {result.source_counts.works} works · {result.source_counts.source_families} independent families</span></div><button onClick={saveHypothesis}>Open in Hypothesis Lab</button></header><nav className="answer-tabs" aria-label="Answer sections">{(['answer','evidence','chronology','citations'] as Tab[]).map(value=><button aria-selected={tab===value} onClick={()=>setTab(value)} key={value}>{value}</button>)}</nav>
      {tab==='answer'&&<div className="answer-reading"><article><p className="eyebrow">Grounded synthesis</p><h2>{result.answer}</h2>{result.uncertainties?.length>0&&<div className="uncertainty-stack"><h3>What remains uncertain</h3>{result.uncertainties.map((value:string)=><p key={value}>{value}</p>)}</div>}</article><aside><h3>Triangulation profile</h3><dl><div><dt>Source families</dt><dd>{result.coverage_profile.independent_source_families}</dd></div><div><dt>Date roles</dt><dd>{result.coverage_profile.date_roles.length}</dd></div><div><dt>Evidence lanes</dt><dd>{result.coverage_profile.evidence_roles.length}</dd></div></dl><p>{result.coverage_profile.description}</p><h3>Source genealogy</h3>{result.source_families.map((family:Record<string,any>)=><div className="family-row" key={family.key}><b>{family.sources.join(', ')}</b><span>{family.claim_count} claims · {family.evidence_roles.join(', ')}</span></div>)}</aside></div>}
      {tab==='evidence'&&<div className="evidence-quadrants"><section><span>01</span><h2>What sources state</h2>{result.source_statements.map((item:Record<string,string>)=><article key={item.claim_id}><p>{item.statement}</p><small>{item.source_title} · {item.locator} · {item.evidence_role}</small></article>)}{!result.source_statements.length&&<p className="board-empty">No direct source statements matched.</p>}</section><section><span>02</span><h2>Interpretations</h2>{result.interpretations.map((item:Record<string,string>)=><article key={item.claim_id}><p>{item.statement}</p><small>{item.source_title} · {item.locator}</small></article>)}{!result.interpretations.length&&<p className="board-empty">No reviewed interpretations matched.</p>}</section><section className="support"><span>03</span><h2>Supporting cards</h2>{result.supporting_evidence.map((item:Record<string,string>,index:number)=><article key={`${item.claim_id}-${index}`}><p>{item.statement}</p><small>{item.evidence_domain}</small></article>)}{!result.supporting_evidence.length&&<p className="board-empty">No reviewed support cards linked.</p>}</section><section className="challenge"><span>04</span><h2>Challenging cards</h2>{result.challenging_evidence.map((item:Record<string,string>,index:number)=><article key={`${item.claim_id}-${index}`}><p>{item.statement}</p><small>{item.evidence_domain}</small></article>)}{!result.challenging_evidence.length&&<p className="board-empty">No reviewed challenge cards linked.</p>}</section></div>}
      {tab==='chronology'&&<div className="ask-chronology"><header><h2>Date roles remain separate</h2><p>Claimed events, composition, witnesses, editions, observations, and natural phenomena are never rendered as one date.</p></header>{result.timeline_items.map((item:Record<string,any>)=><article key={item.temporal_assertion_id}><span className={`date-role role-${item.role}`}>{item.role.replaceAll('_',' ')}</span><div><b>{item.title}</b><p>{item.display_label}</p></div><strong>{item.earliest_year} → {item.latest_year}</strong></article>)}{!result.timeline_items.length&&<p className="empty-state">No reviewed chronology is linked to this packet.</p>}</div>}
      {tab==='citations'&&<div className="citation-ledger"><header><span>ID</span><span>Edition</span><span>Exact locator</span><span>Open</span></header>{result.citations.map((citation:Record<string,string>)=><article key={citation.citation_id}><b>{citation.citation_id}</b><span>{citation.display_label}</span><code>{citation.locator}</code><a href={`/sources/${citation.source_id}`}>Source card</a></article>)}{!result.citations.length&&<p className="empty-state">No citations because the reviewed corpus was insufficient.</p>}</div>}
      {message&&<p className="form-note">{message}</p>}
    </section>}
  </main>;
}
