import { createHash } from "node:crypto";
import { createPool,transaction } from "../src/db";
import { safeFetchMetadata } from "../src/security/fetch";
import { appendAudit } from "../src/domain/services";
import { loadLocalEnv } from "./env";

async function main(){loadLocalEnv();const pool=createPool();const actor="curated-scientific-review";try{const summary=await transaction(pool,async client=>{let claims=0;let assertions=0;
  async function edition(provider:string,externalId:string){const found=await client.query<{id:string}>(`SELECT se.id FROM external_records er JOIN source_providers sp ON sp.id=er.source_provider_id JOIN source_editions se ON se.id=er.source_edition_id WHERE sp.provider_key=$1 AND er.external_id=$2 AND se.review_status IN ('approved','published')`,[provider,externalId]);if(!found.rows[0])throw new Error(`Missing reviewed edition ${provider}:${externalId}`);return found.rows[0].id;}
  async function passage(sourceId:string,locator:string,summary:string){const digest=createHash("sha256").update(summary).digest("hex");let found=await client.query<{id:string}>(`SELECT id FROM passages WHERE source_edition_id=$1 AND locator_value=$2 AND text_hash=$3`,[sourceId,locator,digest]);if(!found.rows[0])found=await client.query<{id:string}>(`INSERT INTO passages (source_edition_id,locator_type,locator_value,safe_summary,text_hash,extraction_confidence,review_status) VALUES ($1,'dataset_record',$2,$3,$4,1,'approved') RETURNING id`,[sourceId,locator,summary,digest]);else await client.query(`UPDATE passages SET review_status='approved' WHERE id=$1`,[found.rows[0].id]);return found.rows[0].id;}
  async function claim(passageId:string,statement:string,caseSlug:string,directness=4,interpretation=0){let found=await client.query<{id:string}>(`SELECT id FROM claims WHERE passage_id=$1 AND statement=$2`,[passageId,statement]);if(!found.rows[0])found=await client.query<{id:string}>(`INSERT INTO claims (passage_id,claim_class,evidence_role,statement,directness,interpretation_level,confidence,review_status,created_by,reviewed_by) VALUES ($1,'empirical_observation','physical_scientific',$2,$3,$4,'high','published',$5,$5) RETURNING id`,[passageId,statement,directness,interpretation,actor]);const file=await client.query<{id:string}>(`SELECT id FROM case_files WHERE slug=$1`,[caseSlug]);for(const [type,id] of [["claim",found.rows[0].id],["passage",passageId]] as const)await client.query(`INSERT INTO case_file_objects (case_file_id,object_type,object_id) VALUES ($1,$2,$3) ON CONFLICT DO NOTHING`,[file.rows[0].id,type,id]);claims++;return found.rows[0].id;}

  const ahpSource=await edition("crossref","10.1038/s41467-019-11701-z");const ahpPassage=(await client.query<{id:string}>(`SELECT id FROM passages WHERE source_edition_id=$1 LIMIT 1`,[ahpSource])).rows[0];if(!ahpPassage)throw new Error("Missing AHP abstract passage");await client.query(`UPDATE passages SET review_status='approved' WHERE id=$1`,[ahpPassage.id]);await claim(ahpPassage.id,"The paper abstract reports at least a 50% reduction in eastward Sahara dust flux during the African Humid Period, wetter conditions reaching approximately 22°N, and limits on inferring vast vegetation across the entire northern and northeastern Sahara.","african-humid-period",3,1);

  for(const item of [{externalId:"occ:212227",id:"212227",slug:"deep-human-timeline",taxon:"Homo sapiens"},{externalId:"occ:212049",id:"212049",slug:"deep-human-timeline",taxon:"Homo erectus"}]){const sourceId=await edition("paleobiodb",item.externalId);const url=`https://paleobiodb.org/data1.2/occs/single.json?id=${item.id}&show=coords,time,strat,ref`;const fetched=await safeFetchMetadata(url,{maxBytes:1_000_000,userAgentPurpose:"curated PBDB occurrence import"});const record=(JSON.parse(new TextDecoder().decode(fetched.content)) as any).records?.[0];if(!record||record.oid!==item.externalId)throw new Error(`PBDB record mismatch ${item.externalId}`);const summary=`PBDB ${record.oid}: ${record.tna}; interval ${record.oei}; age bounds ${record.eag}–${record.lag} Ma; collection ${record.cid}; reference ${record.ref}.`;const p=await passage(sourceId,`${url}#records[0]`,summary);const statement=`The Paleobiology Database occurrence record identifies ${item.taxon} in the ${record.oei} with reported age bounds of ${record.eag} to ${record.lag} million years and links the occurrence to PBDB reference ${record.rid}.`;await client.query(`WITH superseded AS (UPDATE claims SET review_status='retracted',uncertainty_note='Superseded by an atomic citation-safe claim; full bibliographic text remains preserved in the source passage.',updated_at=now() WHERE passage_id=$1 AND created_by=$2 AND review_status='published' AND statement<>$3 RETURNING id) UPDATE temporal_assertions SET review_status='retracted' WHERE source_claim_id IN (SELECT id FROM superseded)`,[p,actor,statement]);const c=await claim(p,statement,item.slug,4,0);const earliest=Math.round(1950-record.eag*1_000_000);const latest=Math.round(1950-record.lag*1_000_000);const exists=await client.query(`SELECT 1 FROM temporal_assertions WHERE target_type='source_edition' AND target_id=$1 AND role='phenomenon_date' AND source_claim_id=$2`,[sourceId,c]);if(!exists.rows[0]){await client.query(`INSERT INTO temporal_assertions (target_type,target_id,role,earliest_year,latest_year,display_label,era_system,precision,dating_method,chronology_model,confidence,source_claim_id,note,review_status) VALUES ('source_edition',$1,'phenomenon_date',$2,$3,$4,'astronomical_year','range','PBDB occurrence age bounds','Ma converted relative to 1950 CE','medium',$5,'Database occurrence interval; not a precise individual lifetime.','approved')`,[sourceId,earliest,latest,`${record.eag}–${record.lag} Ma (${record.oei})`,c]);assertions++;}}

  const noaaSource=await edition("noaa_paleo","2709");const noaaUrl="https://www.ncei.noaa.gov/access/paleo-search/study/search.json?xmlId=2709&limit=1";const noaaFetched=await safeFetchMetadata(noaaUrl,{maxBytes:3_000_000,userAgentPurpose:"curated NOAA dataset import"});const study=(JSON.parse(new TextDecoder().decode(noaaFetched.content)) as any).study?.[0];const data=study?.site?.[0]?.paleoData?.[0];if(study?.xmlId!=="2709"||!data)throw new Error("NOAA study 2709 parse failed");const noaaSummary=`NOAA/WDS study ${study.xmlId}: ${study.studyName}; site ${study.site[0].siteName}; coverage ${data.earliestYear} to ${data.mostRecentYear} ${data.timeUnit} (${data.earliestYearCE} to ${data.mostRecentYearCE} CE conversion).`;const noaaPassage=await passage(noaaSource,`${noaaUrl}#study[0].site[0].paleoData[0]`,noaaSummary);const noaaClaim=await claim(noaaPassage,`NOAA/WDS catalogs Gulf of Mexico deglacial stable-isotope data with reported coverage from ${data.earliestYear} to ${data.mostRecentYear} ${data.timeUnit}; this coverage includes the Younger Dryas interval but does not by itself identify a cause.`,"younger-dryas",4,1);const noaaExists=await client.query(`SELECT 1 FROM temporal_assertions WHERE target_type='source_edition' AND target_id=$1 AND role='phenomenon_date' AND source_claim_id=$2`,[noaaSource,noaaClaim]);if(!noaaExists.rows[0]){await client.query(`INSERT INTO temporal_assertions (target_type,target_id,role,earliest_year,latest_year,display_label,era_system,precision,dating_method,confidence,source_claim_id,note,review_status) VALUES ('source_edition',$1,'phenomenon_date',$2,$3,$4,'astronomical_year','range','NOAA dataset cal yr BP age model','high',$5,'Dataset coverage, not a causal claim about the Younger Dryas.','approved')`,[noaaSource,data.earliestYearCE,data.mostRecentYearCE,`${data.earliestYear}–${data.mostRecentYear} ${data.timeUnit}`,noaaClaim]);assertions++;}
  await client.query(`UPDATE temporal_assertions ta SET review_status='retracted' FROM claims c WHERE c.id=ta.source_claim_id AND c.review_status='retracted' AND ta.review_status IN ('approved','published')`);
  await appendAudit(client,{objectType:"scientific_curation",objectId:"00000000-0000-4000-8000-000000000002",action:"scientific_records_reviewed",actor,after:{claims,assertions}});return{claims_reviewed:claims,assertions_created:assertions};});process.stdout.write(`${JSON.stringify(summary,null,2)}\n`);}finally{await pool.end();}}
main().catch(error=>{process.stderr.write(`${error instanceof Error?error.message:String(error)}\n`);process.exitCode=1;});
