import { createPool, transaction } from "../src/db";
import { safeFetchMetadata } from "../src/security/fetch";
import { appendAudit } from "../src/domain/services";
import { loadLocalEnv } from "./env";

const places = [
  { id:"579885", caseFiles:["atlantis-in-plato"], note:"Representative point from Pleiades for ancient Athens; it is not a boundary." },
  { id:"874621", caseFiles:["sumerian-king-list-long-reigns","flood-traditions-atlas"], note:"Representative point from Pleiades for Nineveh; ancient extent is not represented by this point." },
];

async function main(){loadLocalEnv();const pool=createPool();const actor="curated-place-review";try{let imported=0;await transaction(pool,async client=>{
  for(const item of places){const url=`https://pleiades.stoa.org/places/${item.id}/json`;const response=await safeFetchMetadata(url,{maxBytes:2_000_000,userAgentPurpose:"curated place import"});const payload=JSON.parse(new TextDecoder().decode(response.content)) as {title:string;reprPoint:[number,number];description?:string;uri?:string};if(!payload.title||!Array.isArray(payload.reprPoint)||payload.reprPoint.length!==2)throw new Error(`PARSE_FAILED: Pleiades ${item.id}`);let place=await client.query<{id:string}>(`SELECT id FROM places WHERE external_ids->>'pleiades'=$1`,[item.id]);if(!place.rows[0])place=await client.query<{id:string}>(`INSERT INTO places (preferred_name,place_kind,geometry,public_geometry,uncertainty_type,uncertainty_note,external_ids,review_status) VALUES ($1,'ancient_settlement',ST_SetSRID(ST_MakePoint($2,$3),4326),ST_SetSRID(ST_MakePoint($2,$3),4326),'representative_point',$4,$5::jsonb,'approved') RETURNING id`,[payload.title,payload.reprPoint[0],payload.reprPoint[1],item.note,JSON.stringify({pleiades:item.id,url:payload.uri??url,license:"CC BY 3.0"})]);for(const slug of item.caseFiles){await client.query(`INSERT INTO case_file_objects (case_file_id,object_type,object_id) SELECT id,'place',$2 FROM case_files WHERE slug=$1 ON CONFLICT DO NOTHING`,[slug,place.rows[0].id]);}await appendAudit(client,{objectType:"place",objectId:place.rows[0].id,action:"pleiades_place_reviewed",actor,after:{pleiades_id:item.id,url}});imported++;}
  let atlantis=await client.query<{id:string}>(`SELECT id FROM places WHERE preferred_name='Atlantis (Platonic narrative)'`);if(!atlantis.rows[0])atlantis=await client.query<{id:string}>(`INSERT INTO places (preferred_name,place_kind,uncertainty_type,uncertainty_note,external_ids,review_status) VALUES ('Atlantis (Platonic narrative)','literary','mythical','No factual coordinates are assigned. Candidate-location hypotheses must remain separate from Plato''s literary geography.','{"source":"Timaeus, reviewed Gutenberg excerpt"}'::jsonb,'approved') RETURNING id`);await client.query(`INSERT INTO case_file_objects (case_file_id,object_type,object_id) SELECT id,'place',$1 FROM case_files WHERE slug='atlantis-in-plato' ON CONFLICT DO NOTHING`,[atlantis.rows[0].id]);
});process.stdout.write(`${JSON.stringify({places_reviewed:imported+1},null,2)}\n`);}finally{await pool.end();}}
main().catch(error=>{process.stderr.write(`${error instanceof Error?error.message:String(error)}\n`);process.exitCode=1;});
