import { createPool } from "../src/db";
import { ProviderService } from "../src/connectors/provider-service";
import { seedSyntheticFixtures } from "../src/fixtures/seed";
import { curatedDiscoveryQueries } from "../fixtures/curated-discovery";
import { loadLocalEnv } from "./env";

async function main(){loadLocalEnv();const pool=createPool();const actor="curated-discovery";const batchKey=`ten-case-open-discovery-v1`;try{await seedSyntheticFixtures(pool);const batch=await pool.query<{id:string}>(`INSERT INTO curation_batches (batch_key,description,status,actor) VALUES ($1,'Bounded public/open metadata discovery for the ten packet case files.','running',$2) ON CONFLICT (batch_key) DO UPDATE SET status='running',warnings='[]',warning_count=0,query_count=0,record_count=0,started_at=now(),completed_at=NULL RETURNING id`,[batchKey,actor]);const service=new ProviderService(pool);let recordCount=0;const warnings:string[]=[];for(const item of curatedDiscoveryQueries){try{const caseFile=await pool.query<{id:string}>(`SELECT id FROM case_files WHERE slug=$1`,[item.caseFile]);if(!caseFile.rows[0])throw new Error(`Case file not found: ${item.caseFile}`);const candidates=await service.search(item.provider,item.query,actor,4);for(const candidate of candidates){const recordId=await service.stage(item.provider,candidate,actor);await pool.query(`INSERT INTO case_file_external_records (case_file_id,external_record_id,curation_batch_id,relevance_note) VALUES ($1,$2,$3,$4) ON CONFLICT (case_file_id,external_record_id) DO UPDATE SET curation_batch_id=EXCLUDED.curation_batch_id,relevance_note=EXCLUDED.relevance_note`,[caseFile.rows[0].id,recordId,batch.rows[0].id,item.relevance]);recordCount++;}process.stdout.write(`${item.caseFile} · ${item.provider} · ${candidates.length}\n`);}catch(error){warnings.push(`${item.caseFile}/${item.provider}: ${error instanceof Error?error.message:String(error)}`);}}
await pool.query(`UPDATE curation_batches SET status=$2,query_count=$3,record_count=$4,warning_count=$5,warnings=$6::jsonb,completed_at=now() WHERE id=$1`,[batch.rows[0].id,warnings.length?"completed_with_warnings":"completed",curatedDiscoveryQueries.length,recordCount,warnings.length,JSON.stringify(warnings)]);process.stdout.write(`${JSON.stringify({batch_key:batchKey,queries:curatedDiscoveryQueries.length,records:recordCount,warnings},null,2)}\n`);}finally{await pool.end();}}
main().catch(error=>{process.stderr.write(`${error instanceof Error?error.message:String(error)}\n`);process.exitCode=1;});
